({
    baseUrl: "gz",
    dir: 'gzout',
    //modules: [
    //    { name: 'faceToFace' },
    //    { name: 'GToilCardExcelImport' },
    //    { name: '2', exclude: ['lib/vbstring'], include:['1'] }
    //],
    fileExclusionRegExp: /\.ts$/,
    // optimize: "uglify"
    optimize: "none",
});
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map 
//# sourceMappingURL=build.js.map